### ISSUE TITLE
API key required

### ISSUE THREAD

**Issue by SwPractitioner** [RajeshRP/schooltime-api#1]
Hi!
@RajeshRP 
@stplsdc 
If i have to test this api by sending the requests to the api URL then how do I get the API key i.e. ST-API-KEY to pass along with request as mentioned in http://docs.schooltimeapp.apiary.io/#introduction/requirements-for-apps-using-the-schooltime-api :

`NoteST-API-KEY must be passed in the request header. Comma can be used in the paramenter (https://school-time.co/app2/index.php/api/students?id=9,2,10)`

**Comment by RajeshRP** [comment]
Hello @SwPractitioner, 

This is just the documentation meant for the developers of any training institution that willing to integrate SchoolTime with some other services. The schools must be signed up with SchoolTime to obtain this key. The API key can be obtained from admin login of the school, or the admin can send the support request to obtain the key.

Cheers.

**Comment by SwPractitioner** [comment]
Thanks @RajeshRP for replying.
